// <auto-generated />
using AracKiralamaSitesiCoreProje.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AracKiralamaSitesiCoreProje.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250503120823_ismail")]
    partial class ismail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AracKiralamaSitesiCoreProje.Models.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AracDurum")
                        .HasColumnType("bit");

                    b.Property<int>("AracGunlukFiyat")
                        .HasColumnType("int");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracYakit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AracId");

                    b.ToTable("aracs");
                });

            modelBuilder.Entity("AracKiralamaSitesiCoreProje.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KiralananArac")
                        .HasColumnType("int");

                    b.Property<string>("MusteriAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("musteris");
                });
#pragma warning restore 612, 618
        }
    }
}
